apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mailhog
  namespace: test-istio
spec:
  template:
    metadata:
      labels:
        app: mailhog
        version: v1
    spec:
      containers:
      - image: mailhog/mailhog
        name: mailhog
        ports:
          - containerPort: 1025
          - containerPort: 8025
