kiali:
  enabled: true
  createDemoSecret: true
  contextPath: /
  dashboard:
    grafanaURL: https://grafana.ISTIO_BASIC_URL/
    jaegerURL:  /jaeger

  ingress:
    enabled: true
    hosts:
      - "kiali.ISTIO_BASIC_URL"
    annotations:
      kubernetes.io/tls-acme: "ACTIVATE_TLS"
    tls:
      - secretName: kiali-secret-tls
        hosts: ["kiali.ISTIO_BASIC_URL"]
