apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ab-mesh
  name: ab-mesh
spec:
  selector:
    matchLabels:
      app: ab-mesh
  template:
    metadata:
      labels:
        app: ab-mesh
        type: test
    spec:
      containers:
      - image: nicolaka/netshoot
        name: netshoot
        env:
          - name: TYPE
            value: istio
        command:
          - "sh"
          - "-c"
          - |-
              while sleep 0.`echo $RANDOM%15 | bc`
              do
                result=`curl -v https://mailhog-$TYPE.pcd-2019.aios.sh 2>&1 > /dev/null | grep "^< HTTP"`
                echo "`date +%s` $TYPE $result"
              done
