apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gateway-istio-certificate
  namespace: istio-system
spec:
  secretName: GATEWAY_CREDENTIAL
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "ISTIO_BASIC_URL"
  dnsNames:
    - "ISTIO_BASIC_URL"
    - "*.ISTIO_BASIC_URL"
  acme:
    config:
      - dns01:
          provider: pcd-2019
        domains:
          - "ISTIO_BASIC_URL"
          - "*.ISTIO_BASIC_URL"
