apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gateway-istio
  namespace: istio-system
spec:
  secretName: gateway-istio-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "ISTIO_BASIC_URL"
  dnsNames:
    - "ISTIO_BASIC_URL"
    - "*.ISTIO_BASIC_URL"
  acme:
    config:
      - http01:
          ingressClass: istio
        domains:
          - "ISTIO_BASIC_URL"
          - "*.ISTIO_BASIC_URL"
