apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "mailhog-istio-client-mtls-strict"
  namespace: "test-istio"
spec:
  targets:
    - name: mailhog
  peers:
    - mtls:
        mode: STRICT
