---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $DEFAULT_EMAIL
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
    dns01:
      # List of DNS-01 providers that can solve DNS challenges
      providers:
        - name: pcd-2019
          route53:
            region: "$REGION"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: kube-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: $DEFAULT_EMAIL
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
    dns01:
      # List of DNS-01 providers that can solve DNS challenges
      providers:
        - name: pcd-2019
          route53:
            region: "$REGION"
